version: '3'

services:
    app:
        image: djangobudget:latest
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "127.0.0.1:8000:80"
        env_file: configuration.env
        depends_on:
            -   mariadb

    mariadb:
        image: mariadb:10.7
        volumes:
            - db_data:/var/lib/mysql
        env_file: configuration.env
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
    db_data: